# Generated by Django 4.1 on 2022-11-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('iata_code', models.CharField(max_length=3)),
                ('icao_code', models.CharField(max_length=4)),
                ('rus_code', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=13)),
                ('webpage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_eng', models.CharField(max_length=50)),
                ('city_rus', models.CharField(max_length=50)),
                ('code_eng', models.CharField(max_length=3)),
                ('code_rus', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_city', models.CharField(help_text='Введите город вылета', max_length=50, verbose_name='Город вылета')),
                ('dest_city', models.CharField(help_text='Введите город назначения', max_length=50, verbose_name='Город назначения')),
                ('max_transhipments', models.SmallIntegerField(help_text='Количество пересадок, не более 3', verbose_name='Количество пересадок')),
                ('depart_date', models.DateField(help_text='Введите дату вылета', verbose_name='Дата вылета')),
                ('return_date', models.DateField(help_text='Для перелетов в один конец оставьте пустым', null=True, verbose_name='Дата возвращения')),
                ('num_adults', models.SmallIntegerField(help_text='Не более 10', verbose_name='Количество взрослых пассажиров')),
                ('num_children', models.SmallIntegerField(help_text='Не более 5', null=True, verbose_name='Количество детей')),
                ('num_infants', models.SmallIntegerField(help_text='Не более 1 на каждого взрослого', null=True, verbose_name='Количество младенцев')),
                ('luggage', models.BooleanField(default=False, help_text='Багаж', verbose_name='Багаж')),
                ('search_init_date', models.DateTimeField(auto_now_add=True, help_text='Дата добавления поиска', verbose_name='Дата добавления поиска')),
                ('telegr_acc', models.CharField(help_text='Введите свой телеграм-аккаунт', max_length=50, verbose_name='Телеграм-аккаунт')),
                ('phone_num', models.CharField(help_text='Введите свой телефон', max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.CharField(help_text='Введите свою электронную почту', max_length=30, null=True, verbose_name='Эл. почта')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_search.search')),
            ],
        ),
    ]
