# Generated by Django 4.1 on 2022-10-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('iata_code', models.CharField(max_length=3)),
                ('icao_code', models.CharField(max_length=4)),
                ('rus_code', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=8)),
                ('webpage', models.URLField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_eng', models.CharField(max_length=50)),
                ('city_rus', models.CharField(max_length=50)),
                ('code_eng', models.CharField(max_length=3)),
                ('code_rus', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oneway_flight', models.BooleanField(default=False)),
                ('max_transhipments', models.SmallIntegerField(default=0)),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField(null=True)),
                ('num_adults', models.SmallIntegerField()),
                ('num_children', models.SmallIntegerField(null=True)),
                ('luggage', models.BooleanField(default=False)),
                ('search_init_date', models.DateTimeField(auto_now_add=True)),
                ('telegr_acc', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('depature_city', models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='depature_city', to='flight_search.citycode')),
                ('dest_city', models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dest_city', to='flight_search.citycode')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_search.search')),
            ],
        ),
    ]
