# Generated by Django 4.1 on 2022-08-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegr_acc', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depature_city', models.CharField(max_length=50)),
                ('dest_city', models.CharField(max_length=50)),
                ('oneway_flight', models.BooleanField(default=False)),
                ('max_transhipment', models.SmallIntegerField()),
                ('return_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('num_adults', models.SmallIntegerField()),
                ('num_infants', models.SmallIntegerField()),
                ('num_childs', models.SmallIntegerField()),
                ('search_init', models.DateTimeField(auto_now_add=True)),
                ('search_until', models.DateTimeField()),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_search.seatclass')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_search.traveller')),
            ],
        ),
    ]
