# Generated by Django 4.1 on 2022-08-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='search_init',
            new_name='search_init_date',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='search_until',
            new_name='search_until_date',
        ),
        migrations.AddField(
            model_name='search',
            name='luggage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='search',
            name='seat_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_search.seatclass'),
        ),
        migrations.AlterField(
            model_name='search',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_search.traveller'),
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('link', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_search.search')),
            ],
        ),
    ]
