# Generated by Django 4.1 on 2022-10-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_search', '0002_alter_airportcode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportcode',
            name='webpage',
            field=models.URLField(),
        ),
    ]
