# Generated by Django 4.1 on 2024-10-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flight_search", "0002_searcharchive"),
    ]

    operations = [
        migrations.AddField(
            model_name="airportcode",
            name="airport_type",
            field=models.CharField(
                choices=[
                    ("внутренний", "внутренний"),
                    ("международный", "междунарондый"),
                ],
                default="внутренний",
                max_length=13,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="airportcode",
            name="city_pk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airports",
                to="flight_search.citycode",
            ),
        ),
    ]
