# Generated by Django 4.1 on 2022-10-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_search', '0003_alter_airportcode_webpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='depature_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='dest_city',
            field=models.CharField(max_length=50),
        ),
    ]
